INT-2672 Public URL available at sidevus1 and sideveu2
Siteimprove/CMS-plugin-Wordpress pull request #23
Opened 2023-01-25 18:04 UTC by Flavio-Almeida

2023-01-26 09:05 UTC, jespernpedersen requested changes

2023-01-26 09:05 UTC, jespernpedersen commented on README.md
> +* Added Custom Overlay field.
Is Custom Overlay field from a previous PR?

2023-01-27 04:43 UTC, Flavio-Almeida commented on siteimprove/admin/partials/class-siteimprove-admin-settings.php
> +		<input type="text" id="siteimprove_public_url_field" name="siteimprove_public_url" value="<?php echo esc_attr( get_option( 'siteimprove_public_url' ) ); ?>" maxlength="50" size="50" />
Max length removed

2023-01-30 08:27 UTC, jespernpedersen approved these changes

2023-01-30 08:27 UTC, jespernpedersen commented on siteimprove/admin/partials/class-siteimprove-admin-settings.php
> +		<input type="text" id="siteimprove_overlayjs_file_field" name="siteimprove_overlayjs_file" value="<?php echo esc_attr( get_option( 'siteimprove_overlayjs_file' ) ); ?>" maxlength="50" size="50" />
Since we're touching this line as well, should we remove the maxlength as well?

2023-02-02 00:17 UTC, merged